from europe.models import Country
list_countries = [{'name': 'Austria', 'abbreviation': 'AT', 'population': 9006398, 'currency': 'Euro'}, {'name': 'Belgium', 'abbreviation': 'BE', 'population': 11589623, 'currency': 'Euro'}, {'name': 'Bulgaria', 'abbreviation': 'BG', 'population': 6948445, 'currency': 'Euro'}, {'name': 'Croatia', 'abbreviation': 'HR', 'population': 4105267, 'currency': 'Euro'}, {'name': 'Cyprus', 'abbreviation': 'CY', 'population': 1207539, 'currency': 'Euro'}, {'name': 'Czech Republic', 'abbreviation': 'CZ', 'population': 10708981, 'currency': 'Euro'}, {'name': 'Denmark', 'abbreviation': 'DK', 'population': 5792202, 'currency': 'Euro'}, {'name': 'Estonia', 'abbreviation': 'EE', 'population': 1315635, 'currency': 'Euro'}, {'name': 'Finland', 'abbreviation': 'FI', 'population': 5540720, 'currency': 'euro'}, {'name': 'France', 'abbreviation': 'FR', 'population': 65273511, 'currency': 'euro'}, {'name': 'Germany', 'abbreviation': 'DE', 'population': 83783942, 'currency': 'euro'}, {'name': 'Greece', 'abbreviation': 'EL', 'population': 10423054, 'currency': 'euro'}, {'name': 'Hungary', 'abbreviation': 'HU', 'population': 9660351, 'currency': 'euro'}, {'name': 'Ireland', 'abbreviation': 'IE', 'population': 4937786, 'currency': 'euro'}, {'name': 'Italy', 'abbreviation': 'IT', 'population': 60461826, 'currency': 'euro'}, {'name': 'Latvia', 'abbreviation': 'LV', 'population': 1886198, 'currency': 'euro'}, {'name': 'Lithuania', 'abbreviation': 'LT', 'population': 2722289, 'currency': 'euro'}, {'name': 'Luxembourg', 'abbreviation': 'LU', 'population': 625978, 'currency': 'euro'}, {'name': 'Malta', 'abbreviation': 'MT', 'population': 441543, 'currency': 'euro'}, {'name': 'Netherlands', 'abbreviation': 'NL', 'population': 0, 'currency': 'euro'}, {'name': 'Poland', 'abbreviation': 'PL', 'population': 37846611, 'currency': 'euro'}, {'name': 'Portugal', 'abbreviation': 'PT', 'population': 10196709, 'currency': 'euro'}, {'name': 'Romania', 'abbreviation': 'RO', 'population': 19237691, 'currency': 'euro'}, {'name': 'Slovakia', 'abbreviation': 'SK', 'population': 5459642, 'currency': 'euro'}, {'name': 'Slovenia', 'abbreviation': 'SI', 'population': 2078938, 'currency': 'euro'}, {'name': 'Spain', 'abbreviation': 'ES', 'population': 46754778, 'currency': 'euro'}, {'name': 'Sweden', 'abbreviation': 'SE', 'population': 10099265, 'currency': 'SEK'}]

for cnt in list_countries:
    pais = Country(
        name = cnt['name'],
        sigla = cnt['abbreviation'],
        population = cnt['population'],
        currency = cnt['currency']
    )
    print(pais)
    # pais.save()