# Generated by Django 4.0.1 on 2022-01-30 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_alter_country_options_country_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDP_per_capita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gdp_per_capita', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
            options={
                'verbose_name': 'GDP_per_capita',
                'verbose_name_plural': 'GDP_per_capita',
            },
        ),
        migrations.CreateModel(
            name='GDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gdp', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
            options={
                'verbose_name': 'GDP',
                'verbose_name_plural': 'GDP',
            },
        ),
    ]
