# Generated by Django 4.0.1 on 2022-02-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_sigla'),
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDP_Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gdp_growth', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
            options={
                'verbose_name': 'GDP_Growth',
                'verbose_name_plural': 'GDP_Growth',
            },
        ),
    ]
