# Generated by Django 4.0.1 on 2022-01-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Country'},
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='euro', max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
