# Generated by Django 4.0.1 on 2022-01-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_options_country_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(default='Euro', max_length=50),
        ),
    ]
