# Generated by Django 4.0.1 on 2022-02-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_alter_country_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='sigla',
            field=models.CharField(default='', max_length=5),
        ),
    ]
