# Generated by Django 4.0.1 on 2022-02-25 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sigla', models.CharField(default='', max_length=5)),
                ('population', models.IntegerField(default=0)),
                ('currency', models.CharField(default='Euro', max_length=50)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='GDP_per_capita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gdp_per_capita', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europe.country')),
            ],
            options={
                'verbose_name': 'GDP_per_capita',
                'verbose_name_plural': 'GDP_per_capita',
            },
        ),
        migrations.CreateModel(
            name='GDP_Growth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gdp_growth', models.FloatField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europe.country')),
            ],
            options={
                'verbose_name': 'GDP_Growth',
                'verbose_name_plural': 'GDP_Growth',
            },
        ),
        migrations.CreateModel(
            name='GDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gdp', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europe.country')),
            ],
            options={
                'verbose_name': 'GDP',
                'verbose_name_plural': 'GDP',
            },
        ),
    ]
