# Generated by Django 4.0.1 on 2022-07-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0002_report_title_report_type_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='population',
        ),
    ]
