# Generated by Django 4.0.1 on 2022-02-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0002_tag_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.CharField(choices=[('Menu', 'Menu'), ('Submenu', 'Submenu')], default='Menu', max_length=255),
        ),
    ]
