# Generated by Django 4.0.1 on 2022-07-22 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0003_remove_country_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2000)),
                ('value', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_data', to='europe.country')),
                ('report', models.ForeignKey(limit_choices_to={'group': 'Submenu'}, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='europe.tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='gdp_growth',
            name='country',
        ),
        migrations.RemoveField(
            model_name='gdp_per_capita',
            name='country',
        ),
        migrations.DeleteModel(
            name='GDP',
        ),
        migrations.DeleteModel(
            name='GDP_Growth',
        ),
        migrations.DeleteModel(
            name='GDP_per_capita',
        ),
    ]
