# Generated by Django 4.0.1 on 2022-02-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0003_tag_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='menu',
            field=models.CharField(choices=[('Economy', 'Economy')], default='Economy', max_length=255),
        ),
    ]
