# Generated by Django 4.0.1 on 2022-07-22 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0004_data_report_remove_gdp_growth_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='type_chart',
        ),
    ]
