# Generated by Django 4.0.1 on 2022-07-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0005_remove_report_type_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report',
        ),
        migrations.DeleteModel(
            name='Data_report',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
