# Generated by Django 4.0.1 on 2022-07-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0007_report_data_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='sigla',
            new_name='code',
        ),
    ]
