# Generated by Django 4.0.1 on 2022-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europe', '0010_alter_data_report_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_report',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
